name: Check packages

on: [pull_request]

jobs:
  robotcdnjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download checker
        uses: wei/wget@v1
        with:
          args: https://github.com/cdnjs/tools/releases/latest/download/checker

      - run: sudo chmod +x ./checker

      - name: find PR
        id: pr
        run: |
          number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "##[set-output name=number;]$number"

      - name: find modified packages
        id: diff
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
          prNumber: ${{ steps.pr.outputs.number }}

      - name: lint package
        id: lint
        run: bash ./scripts/lint.sh \
            ${{ steps.diff.outputs.files_modified }} \
            ${{ steps.diff.outputs.files_added }}

      # install glob
      - uses: actions/checkout@v2
        with:
          repository: cdnjs/glob
          path: ./glob
      - run: cd ${{ github.workspace }}/glob && npm install

      - name: compute files
        id: files
        env:
          BOT_BASE_PATH: ${{ github.workspace }}
        run: bash ./scripts/show-files.sh \
            ${{ steps.diff.outputs.files_modified }} \
            ${{ steps.diff.outputs.files_added }}
